development:
  host: localhost
  database: team2011_development

test:
  host: localhost
  database: team2011_test

# set these environment variables on your prod server
production:
  host: localhost
  database: team2011_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
